name: Test Project
on:
    workflow_dispatch:
    push:
        branches:
            - main  
    pull_request:
        types:
            - opened
            - edited
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Download repository
              uses: actions/checkout@v3
            - name: Install NodeJS (unnecessary but for demo)
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Deploying"