name: Dev CI
on:
    workflow_dispatch:
    push:
        branches:
            - main  
    pull_request:
        types:
            - opened
            - edited
jobs:
    BuildContract:
        runs-on: ubuntu-latest
        steps:
            - name: Download repository
              uses: actions/checkout@v3
            - name: Install NodeJS (unnecessary but for demo)
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    Test:
        needs: BuildContract
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Running tests"
    VerifyCodeCoverage:
        needs: Test
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Verifying code coverage"